### PR TITLE
DIOS-2712: Fix typos

### PR DESCRIPTION
**Pull request by dubeyShivank**
Change - 
* `forn` to `for`
* `reasosn` to `reasons`

### CODE REVIEW

**Comment by Jerricho93** [comment]
I see a lot of `reasosn` instances, could those be fixed as well? 😃

**Comment by dubeyShivank** [comment]
> I see a lot of `reasosn` instances, could those be fixed as well? 😃

Done! Thank you for highlighting Manuel!

**Comment by Santiago-Souto** [comment]
@dubeyShivank just as a comment, let's avoid using JIRA identifiers as this is a public repository 😄

**Comment by dubeyShivank** [comment]
Oh sorry @Santiago-Souto ! Completely slipped my mind!

**Pull request merged**
