### PR TITLE
Add description of DTX purpose

### PR DESCRIPTION
**Pull request by Santiago-Souto**
Also, fix typos & update docs

### CODE REVIEW

**Comment by vincentsong** [comment]
Should we also review the translation json files? If not, Could we ignore the generated translation folder  `docs-translations`?

**Review by vincentsong — COMMENTED** [review]
Comments are looks good to me.  But should we also review the translation json files? If not, Could we ignore the generated translation folder `docs-translations`?

**Comment by R-Delfino95** [comment]
> Comments are looks good to me. But should we also review the translation json files? If not, Could we ignore the generated translation folder `docs-translations`?

In the deployment the workflow generates the translation folder. I think It's not necessary to build it each time we modify the docs.
We could add the doc-translation to .gitignore and remove the folder.

**Comment by Santiago-Souto** [comment]
I left #305 open to remove this unnecessary directory. Thanks @vincentsong for pointing it out! Once that is merged we will pull develop and remove does changes.

**Review by R-Delfino95 — APPROVED** [review]

**Pull request merged**
