### PR TITLE
Typescript definitions for diagnose

### PR DESCRIPTION
**Pull request by dubeyShivank**
@Santiago-Souto hoping this is what I need to be doing for ts support?

### CODE REVIEW

**Comment by Santiago-Souto** [comment]
It is the way to go yes! I just do not think the changeset should the created here, as the feature/change is in the `stats` branch, and this is just an add-on to that

**Comment by dubeyShivank** [comment]
Ok I can remove the changeset, thanks!

**Comment by Santiago-Souto** [comment]
Should we create a type for the config object?

**Comment by Santiago-Souto** [comment]
Should `PeerConnectionStats` be updated as well?

**Comment by dubeyShivank** [comment]
> Should `PeerConnectionStats` be updated as well?

I'll do both, thanks!

**Review by Santiago-Souto — APPROVED** [review]
LGTM

**Pull request merged**
